import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import styled from "styled-components";
import HomeBody from "../components/index/HomeBody";
import Product from "../components/index/Product";
import ProDetail from "../components/index/ProDetail";
import Quote from "../components/index/Quote";

export const Container = styled.div`
  max-width: 90%;
  margin: 0 auto;
`;

const Main = styled.main`
  @media screen and (min-width: 1440px) {
    max-width: 1440px;
    margin: 0 auto;
  }
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Dell Marvis Systems | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <HomeBody />
        <Container>
          <Product />
          <ProDetail />
          <Quote />
        </Container>
      </Main>
    </>
  );
}
